name: 'demo_fintech'
version: '1.0.0'
config-version: 2

# Profile configured in ~/.dbt/profiles.yml
# You need to set up BigQuery credentials there
profile: 'demo_fintech'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  demo_fintech:
    staging:
      +materialized: view
    marts:
      +materialized: table
