version: 2

sources:
  - name: raw
    schema: demo_raw
    tables:
      - name: raw_customers
      - name: raw_transactions
      - name: raw_accounts
      - name: raw_subscriptions
      - name: raw_customer_features
      - name: raw_ad_spend
      - name: raw_balances